name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: |
          docker build -t ${{ vars.DOCKER_USERNAME }}/final-project:$GITHUB_SHA -t ${{ vars.DOCKER_USERNAME }}/final-project:latest .
          docker push ${{ vars.DOCKER_USERNAME }}/final-project:$GITHUB_SHA
          docker push ${{ vars.DOCKER_USERNAME }}/final-project:latest
